#!/usr/bin/env -S jenkins-jobs --ignore-cache update
---

- job:
    name: deploy/kvm-deploy
    description: null
    project-type: multibranch
    periodic-folder-trigger: 1d
    prune-dead-branches: true
    number-to-keep: '10'
    days-to-keep: '10'
    script-path: Jenkinsfile
    scm:
      - git:
          url: git@gitlab.intr:vds/vds-xenial.git
          credentials-id: gitlab-git

