#!/usr/bin/env -S jenkins-jobs --ignore-cache update
---
- job:
    name: kvm-templates
    project-type: folder

- job:
    name: kvm-templates/repo
    description: null
    project-type: multibranch
    periodic-folder-trigger: 1d
    prune-dead-branches: true
    number-to-keep: '10'
    days-to-keep: '10'
    script-path: Jenkinsfile
    scm:
      - git:
          url: git@gitlab.intr:vds/vds-xenial.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/bento
    description: null
    project-type: multibranch
    periodic-folder-trigger: 1d
    prune-dead-branches: true
    number-to-keep: '10'
    days-to-keep: '10'
    script-path: Jenkinsfile
    scm:
      - git:
          url: git@gitlab.intr:kvm-templates/bento.git
          credentials-id: gitlab-git

- job: &packer # Template
    name: kvm-templates/packer
    description: null
    project-type: multibranch
    periodic-folder-trigger: 1d
    prune-dead-branches: true
    number-to-keep: '10'
    days-to-keep: '10'
    script-path: Jenkinsfile
    scm:
      - git:
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/select
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-select
    scm:
      - git:
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/centos-6
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-centos-6
    scm:
      - git: &packer-git # Template
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git
          property-strategies:
            all-branches:
              - suppress-scm-triggering: true

- job:
    name: kvm-templates/centos-7
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-centos-7
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/centos-8
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-centos-8
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/debian-8
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-debian-8
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/debian-9
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-debian-9
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/debian-10
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-debian-10
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/debian-8-administration
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-debian-8-administration
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/debian-9-administration
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-debian-9-administration
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/debian-10-administration
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-debian-10-administration
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/ubuntu-14.04
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-ubuntu-14.04
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/ubuntu-16.04
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-ubuntu-16.04
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/ubuntu-18.04
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-ubuntu-18.04
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/ubuntu-20.04
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-ubuntu-20.04
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/nixos-19.09
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-nixos-19.09
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/nixos-20.03
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-nixos-20.03
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/freebsd-12.1
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-freebsd-12.1
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/freebsd-12.1-order
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-freebsd-12.1-order
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

- job:
    name: kvm-templates/freebsd-12.1-resize-disk
    <<: *packer # It's a Packer job
    script-path: .jenkins/jenkinsfile-freebsd-12.1-resize-disk
    scm:
      - git:
          <<: *packer-git # It's a Packer Git repository
          url: git@gitlab.intr:kvm-templates/packer.git
          credentials-id: gitlab-git

