- job:
    name: nixos
    project-type: folder

- job: &job # Template
    name: nixos/web
    project-type: multibranch
    periodic-folder-trigger: 1d
    prune-dead-branches: true
    number-to-keep: '100'
    days-to-keep: '30'
    script-path: Jenkinsfile
    scm: [ git: { url: git@gitlab.intr:nixos/web.git } ]

- job:
    <<: *job
    name: nixos/jenkins
    scm: [ git: { url: git@gitlab.intr:nixos/jenkins.git } ]

- job:
    <<: *job
    name: nixos/ns
    scm: [ git: { url: git@gitlab.intr:nixos/ns.git } ]

- job:
    <<: *job
    name: nixos/router-office
    scm: [ git: { url: git@gitlab.intr:nixos/router-office.git } ]

- job:
    <<: *job
    name: nixos/nginx
    scm: [ git: { url: git@gitlab.intr:nixos/nginx.git } ]
- job:
    <<: *job
    name: nixos/pop
    scm: [ git: { url: git@gitlab.intr:nixos/pop.git } ]
- job:
    <<: *job
    name: nixos/kvm
    scm: [ git: { url: git@gitlab.intr:nixos/kvm.git } ]
- job:
    <<: *job
    name: nixos/webmail
    scm: [ git: { url: git@gitlab.intr:nixos/webmail.git } ]
- job:
    <<: *job
    name: nixos/swarm
    scm: [ git: { url: git@gitlab.intr:nixos/swarm.git } ]
- job:
    <<: *job
    name: nixos/ispconfig
    scm:
      - git:
          url: git@gitlab.intr:nixos/ispconfig.git
          discover-tags: true
          build-strategies:
            - tags:
                ignore-tags-newer-than: 7
            - regular-branches: true
- job:
    <<: *job
    name: nixos/vm
    scm: [ git: { url: git@gitlab.intr:nixos/vm.git } ]
